"""
    solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing,
          atol=1.0e-12, rtol=1.0e-12, itermax=1.0e4, verbose=false)

Solve the nonlinear residual system generated by composite model `c` with a
Newton-Raphson iteration and backtracking line search.

`x` is the current solver vector, usually from `initial_guess_x`. `vars`
contains prescribed differentiable inputs such as `ε` and `θ`; `others`
contains nondifferentiable auxiliary values such as `dt`, `τ0`, and `P0`.

For tensor-valued strain rates, the solver applies
`effective_strain_rate_correction` and solves in terms of the second invariant
of the corrected effective strain-rate tensor.

# Keywords
- `xnorm0`: normalization vector for residual norms. If `nothing`, ones are used.
- `atol`: absolute residual tolerance.
- `rtol`: relative residual tolerance against the initial residual.
- `itermax`: maximum Newton iterations.
- `verbose`: print the final iteration count, residual norm, and line-search step.
"""
function solve(c::AbstractCompositeModel, x::SVector, vars0, others; xnorm0=nothing, atol::Float64 = 1.0e-12, rtol::Float64 = 1.0e-12, itermax = 1.0e4, verbose::Bool = false)
   
    # Pre-correct ONLY the direct elastic leafs of the outer composite
    # (simple Maxwell backstress).  Tensor arithmetic is used here so that
    # second_invariant(ε + τ0/(2G·dt)) is evaluated correctly even for
    # non-coaxial ε/τ0 pairs.
    # ParallelModel branch corrections are handled implicitly inside
    # compute_residual via subtract_elastic_correction, so they must NOT be
    # included here to avoid double-counting.
    ε_corr = _direct_leaf_elastic_correction(c, vars0.ε, others)
    εII    = second_invariant_value(vars0.ε .+ ε_corr)
    vars   = merge(vars0, (; ε = εII))

    # vars = merge((; ε = εII), vars0)
    xnorm = correct_xnorm(x, xnorm0)
    r     = compute_residual(c, x, vars, others)   # initial residual
    
    it = 0
    er = Inf
    er0 = mynorm(r, xnorm)

    α = 1e0
    while er > atol && er > rtol * er0
        it += 1

        J = ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)
        # r, J = value_and_jacobian(y -> compute_residual(c, y, vars, others), AutoForwardDiff(), x)
        Δx = backsolve(J, r)
        if it > 1 
            α = bt_line_search(Δx, x, c, vars, others, xnorm; α = 1.0, ρ = 0.5, lstol = 0.95, α_min = 0.1)
        end
        x += α .* Δx

        # check convergence
        r = compute_residual(c, x, vars, others)
        er = mynorm(r, xnorm)

        it > itermax && break

        # ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
        # ε_eff  = vars0.ε .+ ε_corr
        # εII    = second_invariant_value(ε_eff)
        # vars   = merge(vars0, (; ε = εII)) # this mames it type unstable; TODO

    end
    if verbose && it > 1
        println("Iterations: $it, Error: $er, α = $α")
    end
    return x
end

"""
    bt_line_search(Δx, x, composite, vars, others, xnorm; α=1.0, ρ=0.5, lstol=0.9, α_min=1.0e-8)

Backtracking line search that repeatedly shrinks `α` by `ρ` until the residual
norm at `x + α * Δx` is at most `lstol` times the current residual norm.
"""
function bt_line_search(Δx, x, composite, vars, others, xnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)

    perturbed_x = @. x + α * Δx
    r = compute_residual(composite, x, vars, others)
    rnorm = mynorm(r, xnorm)

    # Iterate unless step length becomes too small
    while α > α_min
        # Apply scaled update
        perturbed_x = @. x + α * Δx

        # Get updated residual
        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)

        # Check whether residual is sufficiently reduced
        if perturbed_rnorm ≤ lstol * rnorm
            break
        end

        # Bisect step length
        α *= ρ
    end

    return α
end

"""
    mynorm(x, y)

Return a normalized L1-like norm `sum(abs(x[i] / y[i]))`, skipping entries whose
normalization factor is zero.
"""
@generated function mynorm(x::SVector{N, T}, y::SVector{N}) where {N, T}
    return quote
        @inline
        v = zero(T)
        Base.@nexprs $N i -> begin
            xi = @inbounds x[i]
            yi = @inbounds y[i]
            v += !iszero(yi) * abs(xi / yi)
        end
        return v
    end
end

@inline backsolve(J::SVector{1}, r::SVector{1})   = SA[-r[1] * inv(J[1])]
@inline backsolve(J::SMatrix{1,1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J, r) = J \ -r
