using TimerOutputs
# function solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing, atol::Float64 = 1.0e-9, rtol::Float64 = 1.0e-9, itermax = 1.0e4, verbose::Bool = false, elastic_correction=true)
   
#     # if elastic_correction
#     #     ε_correction = effective_strain_rate_correction(c, vars, others)
#     #     vars = merge(vars, (; ε = vars.ε + ε_correction))
#     # end

#     xnorm = correct_xnorm(x, xnorm0)
#     #xnorm = xnorm0 === nothing ? ones(size(x)) : xnorm0
    
#     r   = compute_residual(c, x, vars, others)   # initial residual
#     it  = 0
#     er  = Inf
#     er0 = mynorm(r, xnorm)

#     local α
#     while er > atol #|| (er > rtol * er0 && it>1)
#         it += 1

#         J = ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)
#         Δx = J \ -r
#         #α = bt_line_search_armijo(Δx, J, x, xnorm, c, vars, others, α_min = 1.0e-8, c=0.9)
#         α = bt_line_search(Δx, x, c, vars, others, xnorm; α = 1.0, ρ = 0.5, lstol = 0.95, α_min = 0.1)
#         x += α .* Δx

#         # check convergence
#         r = compute_residual(c, x, vars, others)
#         er = mynorm(r, xnorm)

#         it > itermax && break
#         #if verbose
#         #    println("Iterations: $it, Error: $er, α = $α")
#         #end
#     end
#     if verbose
#         println("Iterations: $it, Error: $er, α = $α")
#     end
#     return x
# end

"""
    solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing,
          atol=1.0e-12, rtol=1.0e-12, itermax=1.0e4, verbose=false)

Solve the nonlinear residual system generated by composite model `c` with a
Newton-Raphson iteration and backtracking line search.

`x` is the current solver vector, usually from `initial_guess_x`. `vars`
contains prescribed differentiable inputs such as `ε` and `θ`; `others`
contains nondifferentiable auxiliary values such as `dt`, `τ0`, and `P0`.

For tensor-valued strain rates, the solver applies
`effective_strain_rate_correction` and solves in terms of the second invariant
of the corrected effective strain-rate tensor.

# Keywords
- `xnorm0`: normalization vector for residual norms. If `nothing`, ones are used.
- `atol`: absolute residual tolerance.
- `rtol`: relative residual tolerance against the initial residual.
- `itermax`: maximum Newton iterations.
- `verbose`: print the final iteration count, residual norm, and line-search step.
"""
function solve(c::AbstractCompositeModel, x::SVector, vars0, others; xnorm0=nothing, atol::Float64 = 1.0e-12, rtol::Float64 = 1.0e-12, itermax = 1.0e4, verbose::Bool = false)
   
    ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
    ε_eff = vars0.ε .+ ε_corr
    εII   = second_invariant_value(ε_eff)
    
    # NOTE: be careful with the order of variables here
    # as the effective strain rate IS ALWAYS THE FIRST
    vars = merge(vars0, (; ε = εII))
    # vars = merge((; ε = εII), vars0)
    
    xnorm = correct_xnorm(x, xnorm0)
    r     = compute_residual(c, x, vars, others)   # initial residual
    # @show εII x r
    
    it = 0
    er = Inf
    er0 = mynorm(r, xnorm)

    local α
    while er > atol && er > rtol * er0
        it += 1

        J = ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)
        Δx = J \ -r
        #α = bt_line_search_armijo(Δx, J, x, xnorm, c, vars, others, α_min = 1.0e-8, c=0.9)
        α = bt_line_search(Δx, x, c, vars, others, xnorm; α = 1.0, ρ = 0.5, lstol = 0.95, α_min = 0.1)
        x += α .* Δx

        # check convergence
        r = compute_residual(c, x, vars, others)
        er = mynorm(r, xnorm)

        it > itermax && break

        ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
        ε_eff  = vars0.ε .+ ε_corr
        εII    = second_invariant_value(ε_eff)
        vars   = merge(vars0, (; ε = εII))
        
    end
    if verbose
        println("Iterations: $it, Error: $er, α = $α")
    end
    return x
end

"""
    solve_timed(c, x, vars, others; tol=1.0e-9, itermax=1.0e4, verbose=false)

Debugging variant of `solve` that records coarse timing information with
`TimerOutputs` and displays the timing table before returning the final `x`.
"""
function solve_timed(c::AbstractCompositeModel, x::SVector, vars, others; tol::Float64 = 1.0e-9, itermax = 1.0e4, verbose::Bool = false)

    it = 0
    er = Inf
    local α
    to = TimerOutput()
    @timeit to "Newton-Raphson Iterations" while er > tol
        it += 1
        @timeit to "residual" r = compute_residual(c, x, vars, others)
        @timeit to "jacobian" J = ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)
        @timeit to "backlash" Δx = J \ r
        @timeit to "line search" α = bt_line_search(Δx, J, x, r, c, vars, others)
        @timeit to "update solution" x -= α .* Δx
        # check convergence
        @timeit to "convergence check" er = mynorm(Δx, x)
        if verbose
            println("Iterations: $it, Error: $er, α = $α")
        end
        it > itermax && break
    end
    display(to)
    if verbose
        println("Iterations: $it, Error: $er, α = $α")
    end
    return x
end

"""
    bt_line_search_armijo(Δx, J, x, xnorm, composite, vars, others; α=1.0, ρ=0.5, c=1.0e-4, α_min=1.0e-8)

Backtracking line search using an Armijo-style sufficient decrease condition for
the residual norm.
"""
function bt_line_search_armijo(Δx, J, x, xnorm, composite, vars, others; α = 1.0, ρ = 0.5, c = 1.0e-4, α_min = 1.0e-8)

    r = compute_residual(composite, x, vars, others)
    rnorm = mynorm(r, xnorm)
    J_times_Δx = J * Δx
    while α > α_min
        perturbed_x = @. x + α * Δx

        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)

        armijo_condition = perturbed_rnorm^2 ≤ rnorm^2 + c * α * (J_times_Δx ⋅ Δx)
        armijo_condition && break

        α *= ρ
    end
    return α
end


"""
    bt_line_search(Δx, x, composite, vars, others, xnorm; α=1.0, ρ=0.5, lstol=0.9, α_min=1.0e-8)

Backtracking line search that repeatedly shrinks `α` by `ρ` until the residual
norm at `x + α * Δx` is at most `lstol` times the current residual norm.
"""
function bt_line_search(Δx, x, composite, vars, others, xnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)

    perturbed_x = @. x + α * Δx
    r = compute_residual(composite, x, vars, others)
    rnorm = mynorm(r, xnorm)

    # Iterate unless step length becomes too small
    while α > α_min
        # Apply scaled update
        perturbed_x = @. x + α * Δx

        # Get updated residual
        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)

        # Check whether residual is sufficiently reduced
        if perturbed_rnorm ≤ lstol * rnorm
            break
        end

        # Bisect step length
        α *= ρ
    end

    return α
end

"""
    mynorm(x, y)

Return a normalized L1-like norm `sum(abs(x[i] / y[i]))`, skipping entries whose
normalization factor is zero.
"""
@generated function mynorm(x::SVector{N, T}, y::SVector{N}) where {N, T}
    return quote
        @inline
        v = zero(T)
        Base.@nexprs $N i -> begin
            xi = @inbounds x[i]
            yi = @inbounds y[i]
            v += !iszero(yi) * abs(xi / yi)
        end
        return v
    end
end
